"""Emit Rust sources for embedded test clips (audio_sample.rs, audio_samples/*.rs)."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import List, Tuple

import numpy as np
import tensorflow as tf

TestClip = Tuple[str, np.ndarray, str]


def collect_test_clips_for_rs(
    root: Path,
    sample_rate: int,
    target_len: int,
    num_per_label: int = 2,
) -> List[TestClip]:
    """Collect a small, fixed set of test clips for Rust."""

    keras = tf.keras
    raw_sample_ds = keras.utils.audio_dataset_from_directory(
        root,
        labels="inferred",
        sampling_rate=sample_rate,
        batch_size=1,
        shuffle=False,
    )

    clips_by_label: dict[int, List[np.ndarray]] = {}
    for audio_batch, label_batch in raw_sample_ds.unbatch():
        label_idx = int(label_batch.numpy())
        if label_idx not in clips_by_label:
            clips_by_label[label_idx] = []
        if len(clips_by_label[label_idx]) < num_per_label:
            audio_1d = np.asarray(audio_batch.numpy(), dtype=np.float32).reshape(-1)
            if audio_1d.size >= target_len:
                fixed = audio_1d[:target_len]
            else:
                fixed = np.zeros(target_len, dtype=np.float32)
                fixed[: audio_1d.size] = audio_1d
            clips_by_label[label_idx].append(fixed)
        if (
            all(len(v) >= num_per_label for v in clips_by_label.values())
            and len(clips_by_label) >= 2
        ):
            break

    if len(clips_by_label) < 2:
        raise RuntimeError("Expected at least two labels in testing dataset.")

    ordered: List[TestClip] = []
    for i in range(num_per_label):
        for label_idx in sorted(clips_by_label.keys()):
            label_name = "target    " if label_idx == 1 else "non_target"
            audio = clips_by_label[label_idx][i]
            rel_path = f"dataset/testing/{label_name}/sample_{i + 1}.wav"
            ordered.append((label_name, audio, rel_path))

    return ordered


def write_audio_sample_rs(
    out_path: Path,
    clips: List[TestClip],
    sample_rate: int,
    generator_name: str = "building_tensorflow/cnn_time.ipynb",
) -> None:
    """Write a Rust audio_sample.rs file compatible with the TinyChirp runner (f32 mel path)."""

    rs: List[str] = []
    rs.append(f"// Generated by {generator_name}\n")
    rs.append(f"pub const SAMPLE_RATE: usize = {sample_rate};\n\n")
    rs.append("pub struct TestClip {\n")
    rs.append("    pub expected_label: &'static str,\n")
    rs.append("    pub audio: &'static [f32],\n")
    rs.append("}\n\n")

    for i, (_label, audio, _rel_path) in enumerate(clips, 1):
        audio_vals = ", ".join(f"{float(v):.8f}" for v in np.asarray(audio).reshape(-1))
        rs.append(f"pub const CLIP_{i}: &[f32] = &[{audio_vals}];\n\n")

    rs.append(f"pub const TEST_CLIPS: [TestClip; {len(clips)}] = [\n")
    for i, (label, _audio, _rel_path) in enumerate(clips, 1):
        rs.append("    TestClip {\n")
        rs.append(f'        expected_label: "{label}",\n')
        rs.append(f"        audio: CLIP_{i},\n")
        rs.append("    },\n")
    rs.append("];\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(rs), encoding="utf-8")


def make_time_feature_fn(target_len: int) -> Callable[[np.ndarray], np.ndarray]:
    """Return a function that pads/crops raw audio like `audio_raw::prepare`."""

    def fn(audio: np.ndarray) -> np.ndarray:
        # Accept (time,), (time, 1), or any shape that can be flattened.
        out = np.asarray(audio, dtype=np.float32).reshape(-1)
        if out.size >= target_len:
            return out[:target_len]

        padded = np.zeros(target_len, dtype=np.float32)
        padded[: out.size] = out
        return padded

    return fn


def write_audio_sample_quantized_rs(
    out_path: Path,
    clips: List[TestClip],
    sample_rate: int,
    tflite_path: Path,
    feature_fn: Callable[[np.ndarray], np.ndarray],
    generator_name: str,
) -> None:
    """Write per-model quantized i8 clips for `BirdModel::predict_quantized`."""

    tflite_path = Path(tflite_path)
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    in_scale, in_zp = inp["quantization"]
    if in_scale == 0:
        raise ValueError("TFLite quantization scale is 0.")
    if inp["dtype"] != np.int8:
        raise ValueError(
            f"Expected int8 model input for quantized export, got {inp['dtype']}"
        )

    qmin, qmax = -128, 127
    shape = inp["shape"]
    expected_elems = int(
        np.prod([max(1, int(d)) for d in shape if d is not None and int(d) > 0])
    )
    if expected_elems <= 0:
        raise ValueError(f"Invalid TFLite input shape: {inp['shape']}")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rs: List[str] = []
    rs.append(f"// Generated by {generator_name}\n")
    rs.append(
        f"// TFLite input quantization (documentation): scale={in_scale}, zero_point={in_zp}\n"
    )
    rs.append(f"pub const SAMPLE_RATE: usize = {sample_rate};\n\n")
    rs.append("pub struct TestClip {\n")
    rs.append("    pub expected_label: &'static str,\n")
    rs.append("    pub input: &'static [i8],\n")
    rs.append("}\n\n")

    for i, (_label, audio, _rel_path) in enumerate(clips, 1):
        feats = feature_fn(audio).astype(np.float32).reshape(-1)
        if feats.size != expected_elems:
            raise ValueError(
                f"Feature length {feats.size} != TFLite input elements {expected_elems} "
                f"(shape {inp['shape']})"
            )
        q = np.clip(np.round(feats / in_scale) + in_zp, qmin, qmax).astype(np.int8)
        vals = ", ".join(str(int(v)) for v in q)
        rs.append(f"pub const CLIP_{i}: &[i8] = &[{vals}];\n\n")

    rs.append(f"pub const TEST_CLIPS: [TestClip; {len(clips)}] = [\n")
    for i, (label, _audio, _rel_path) in enumerate(clips, 1):
        rs.append("    TestClip {\n")
        rs.append(f'        expected_label: "{label}",\n')
        rs.append(f"        input: CLIP_{i},\n")
        rs.append("    },\n")
    rs.append("];\n")

    out_path.write_text("".join(rs), encoding="utf-8")
