"""Emit Rust sources for embedded test clips (audio_sample.rs, audio_samples/*.rs)."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import List, Tuple

import numpy as np
import tensorflow as tf

TestClip = Tuple[str, np.ndarray, str]


def collect_test_clips_for_rs(
    root: Path,
    sample_rate: int,
    target_len: int,
    num_per_label: int = 2,
) -> List[TestClip]:
    """Collect a small, fixed set of test clips for Rust."""

    keras = tf.keras
    raw_sample_ds = keras.utils.audio_dataset_from_directory(
        root,
        labels="inferred",
        sampling_rate=sample_rate,
        batch_size=1,
        shuffle=False,
    )

    clips_by_label: dict[int, List[np.ndarray]] = {}
    for audio_batch, label_batch in raw_sample_ds.unbatch():
        label_idx = int(label_batch.numpy())
        if label_idx not in clips_by_label:
            clips_by_label[label_idx] = []
        if len(clips_by_label[label_idx]) < num_per_label:
            audio_1d = np.asarray(audio_batch.numpy(), dtype=np.float32).reshape(-1)
            if audio_1d.size >= target_len:
                fixed = audio_1d[:target_len]
            else:
                fixed = np.zeros(target_len, dtype=np.float32)
                fixed[: audio_1d.size] = audio_1d
            clips_by_label[label_idx].append(fixed)
        if (
            all(len(v) >= num_per_label for v in clips_by_label.values())
            and len(clips_by_label) >= 2
        ):
            break

    if len(clips_by_label) < 2:
        raise RuntimeError("Expected at least two labels in testing dataset.")

    ordered: List[TestClip] = []
    for i in range(num_per_label):
        for label_idx in sorted(clips_by_label.keys()):
            label_name = "target    " if label_idx == 1 else "non_target"
            audio = clips_by_label[label_idx][i]
            rel_path = f"dataset/testing/{label_name}/sample_{i + 1}.wav"
            ordered.append((label_name, audio, rel_path))

    return ordered


def write_audio_sample_rs(
    out_path: Path,
    clips: List[TestClip],
    sample_rate: int,
    generator_name: str = "building_tensorflow/cnn_time.ipynb",
) -> None:
    """Write a Rust audio_sample.rs file compatible with the TinyChirp runner (f32 mel path)."""

    rs: List[str] = []
    rs.append(f"// Generated by {generator_name}\n")
    rs.append(f"pub const SAMPLE_RATE: usize = {sample_rate};\n\n")
    rs.append("pub struct TestClip {\n")
    rs.append("    pub expected_label: &'static str,\n")
    rs.append("    pub audio: &'static [f32],\n")
    rs.append("}\n\n")

    for i, (_label, audio, _rel_path) in enumerate(clips, 1):
        audio_vals = ", ".join(f"{float(v):.8f}" for v in np.asarray(audio).reshape(-1))
        rs.append(f"pub const CLIP_{i}: &[f32] = &[{audio_vals}];\n\n")

    rs.append(f"pub const TEST_CLIPS: [TestClip; {len(clips)}] = [\n")
    for i, (label, _audio, _rel_path) in enumerate(clips, 1):
        rs.append("    TestClip {\n")
        rs.append(f'        expected_label: "{label}",\n')
        rs.append(f"        audio: CLIP_{i},\n")
        rs.append("    },\n")
    rs.append("];\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(rs), encoding="utf-8")


def make_time_feature_fn(target_len: int) -> Callable[[np.ndarray], np.ndarray]:
    """Return a function that pads/crops raw audio like `audio_raw::prepare`."""

    def fn(audio: np.ndarray) -> np.ndarray:
        # Accept (time,), (time, 1), or any shape that can be flattened.
        out = np.asarray(audio, dtype=np.float32).reshape(-1)
        if out.size >= target_len:
            return out[:target_len]

        padded = np.zeros(target_len, dtype=np.float32)
        padded[: out.size] = out
        return padded

    return fn


def make_mel_feature_fn(target_audio_len: int) -> Callable[[np.ndarray], np.ndarray]:
    """Pad/crop audio then run the same log-mel pipeline as training."""
    from utils import create_log_mel_spectrogram

    time_fn = make_time_feature_fn(target_audio_len)

    def fn(audio: np.ndarray) -> np.ndarray:
        x = time_fn(audio)
        mel = create_log_mel_spectrogram(tf.constant(x, dtype=tf.float32)).numpy()
        return mel.reshape(-1)

    return fn


def write_sample_input_c(
    src_dir: Path,
    clip: TestClip,
    tflite_path: Path,
    feature_fn: Callable[[np.ndarray], np.ndarray],
    generator_name: str,
) -> None:
    """Write src/sample_input.[ch] for the Zephyr/Axon firmware: one clip,
    fed through `feature_fn` and quantized with the tflite input scale."""

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    in_scale, in_zp = inp["quantization"]
    if in_scale == 0:
        raise ValueError("TFLite input not int8-quantized.")

    label, audio, _rel = clip
    feats = feature_fn(audio).astype(np.float32).reshape(-1)
    q = np.clip(np.round(feats / in_scale) + in_zp, -128, 127).astype(np.int8)

    src_dir = Path(src_dir)
    src_dir.mkdir(parents=True, exist_ok=True)

    (src_dir / "sample_input.h").write_text(
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#include <stddef.h>\n\n"
        "extern const int8_t g_sample_input[];\n"
        "extern const size_t g_sample_input_len;\n"
        "extern const char *const g_sample_expected_label;\n\n"
        "#ifdef MEL_FROM_RAW\n"
        '#include "generated_data/sample_input_meta.h"\n'
        "extern const int16_t g_sample_raw_audio[];\n"
        "extern const size_t  g_sample_raw_audio_len;\n"
        "extern const int16_t g_hann_window_q15[];\n"
        "extern const int16_t g_mel_matrix_q15[];\n"
        "extern const float   g_input_quant_scale;\n"
        "extern const int32_t g_input_quant_zp;\n"
        "extern const char *const g_sample_raw_expected_label;\n"
        "#endif\n"
    )

    lines = []
    for i in range(0, len(q), 16):
        chunk = q[i:i + 16]
        lines.append("    " + ", ".join(f"{int(v):>4d}" for v in chunk) + ",")
    body = "\n".join(lines)

    (src_dir / "sample_input.c").write_text(
        f"// generated by {generator_name} — "
        f"{tflite_path.name}, in_quant=({in_scale:g}, {in_zp}), len={len(q)}\n"
        '#include "sample_input.h"\n\n'
        f"const int8_t g_sample_input[] = {{\n{body}\n}};\n"
        f"const size_t g_sample_input_len = {len(q)};\n"
        f'const char *const g_sample_expected_label = "{label.strip()}";\n'
    )


def _pad_or_crop(audio: np.ndarray, n: int) -> np.ndarray:
    audio = np.asarray(audio, dtype=np.float32).reshape(-1)
    if audio.size >= n:
        return audio[:n]
    out = np.zeros(n, dtype=np.float32)
    out[: audio.size] = audio
    return out


def _to_q15(x: np.ndarray) -> np.ndarray:
    return np.clip(np.round(np.asarray(x) * 32767.0), -32768, 32767).astype(np.int16)


def write_sample_input_raw_c(
    src_dir: Path,
    clips: List[TestClip],
    tflite_path: Path,
    generator_name: str,
) -> None:
    from utils import (
        SAMPLE_RATE,
        FRAME_LENGTH,
        FRAME_STEP,
        FFT_LENGTH_MEL,
        NUM_MEL_BINS_MEL,
        TARGET_FRAMES_MEL,
        TARGET_AUDIO_LEN_MEL,
        LOWER_EDGE_HERTZ,
        UPPER_EDGE_HERTZ,
        build_rust_mel_matrix,
        create_log_mel_spectrogram,
    )

    fft_bins = FFT_LENGTH_MEL // 2

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    in_scale, in_zp = interpreter.get_input_details()[0]["quantization"]
    if in_scale == 0:
        raise ValueError("TFLite input not int8-quantized.")

    n = np.arange(FRAME_LENGTH, dtype=np.float64)
    hann = 0.5 - 0.5 * np.cos(2.0 * np.pi * n / (FRAME_LENGTH - 1))
    hann_i16 = _to_q15(hann)

    k = np.arange(fft_bins, dtype=np.float64)
    twiddle = np.empty(2 * fft_bins, dtype=np.float32)
    twiddle[0::2] = np.cos(-2.0 * np.pi * k / FFT_LENGTH_MEL)
    twiddle[1::2] = np.sin(-2.0 * np.pi * k / FFT_LENGTH_MEL)

    _, mel_tf = build_rust_mel_matrix(
        num_mel_bins=NUM_MEL_BINS_MEL,
        fft_length_mel=FFT_LENGTH_MEL,
        frame_length=FRAME_LENGTH,
        sample_rate=SAMPLE_RATE,
        lower_edge_hz=LOWER_EDGE_HERTZ,
        upper_edge_hz=UPPER_EDGE_HERTZ,
    )
    mel_i16 = _to_q15(mel_tf.numpy().T)

    src_dir = Path(src_dir)
    data_dir = src_dir / "generated_data"
    data_dir.mkdir(parents=True, exist_ok=True)

    labels = []
    for i, (label, audio, _rel) in enumerate(clips):
        audio_f = _pad_or_crop(audio, TARGET_AUDIO_LEN_MEL)
        mel = create_log_mel_spectrogram(tf.constant(audio_f)).numpy().reshape(-1)
        mel_q8 = np.clip(np.round(mel / in_scale) + in_zp, -128, 127).astype(np.int8)
        (data_dir / f"sample_audio_{i}.bin").write_bytes(_to_q15(audio_f).tobytes())
        (data_dir / f"sample_mel_{i}.bin").write_bytes(mel_q8.tobytes())
        labels.append(label.strip())

    (data_dir / "hann_q15.bin").write_bytes(hann_i16.tobytes())
    (data_dir / "hann_even_q15.bin").write_bytes(hann_i16[0::2].tobytes())
    (data_dir / "hann_odd_q15.bin").write_bytes(hann_i16[1::2].tobytes())
    (data_dir / "hann_f32.bin").write_bytes(hann.astype(np.float32).tobytes())
    (data_dir / "twiddle_f32.bin").write_bytes(twiddle.tobytes())
    (data_dir / "mel_matrix_q15.bin").write_bytes(mel_i16.reshape(-1).tobytes())

    label_defines = "\n".join(
        f'#define SAMPLE_CLIP_{i}_LABEL  "{lbl}"' for i, lbl in enumerate(labels)
    )
    (data_dir / "sample_input_meta.h").write_text(
        "#pragma once\n\n"
        f"#define MEL_SAMPLE_RATE       {SAMPLE_RATE}\n"
        f"#define MEL_FRAME_LENGTH      {FRAME_LENGTH}\n"
        f"#define MEL_FRAME_STEP        {FRAME_STEP}\n"
        f"#define MEL_TARGET_FRAMES     {TARGET_FRAMES_MEL}\n"
        f"#define MEL_NUM_BINS          {NUM_MEL_BINS_MEL}\n"
        f"#define MEL_FFT_BINS          {fft_bins}\n"
        f"#define MEL_FFT_LENGTH_LOG2   {int(np.log2(FFT_LENGTH_MEL))}\n"
        f"#define MEL_AUDIO_LEN         {TARGET_AUDIO_LEN_MEL}\n\n"
        f"#define MEL_INPUT_QUANT_SCALE ({float(in_scale):.10g}f)\n"
        f"#define MEL_INPUT_QUANT_ZP    {int(in_zp)}\n\n"
        f"#define N_SAMPLE_CLIPS        {len(labels)}\n"
        f"{label_defines}\n"
    )


def write_audio_sample_quantized_rs(
    out_path: Path,
    clips: List[TestClip],
    sample_rate: int,
    tflite_path: Path,
    feature_fn: Callable[[np.ndarray], np.ndarray],
    generator_name: str,
) -> None:
    """Write per-model quantized i8 clips for `BirdModel::predict_quantized`."""

    tflite_path = Path(tflite_path)
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    in_scale, in_zp = inp["quantization"]
    if in_scale == 0:
        raise ValueError("TFLite quantization scale is 0.")
    if inp["dtype"] != np.int8:
        raise ValueError(
            f"Expected int8 model input for quantized export, got {inp['dtype']}"
        )

    qmin, qmax = -128, 127
    shape = inp["shape"]
    expected_elems = int(
        np.prod([max(1, int(d)) for d in shape if d is not None and int(d) > 0])
    )
    if expected_elems <= 0:
        raise ValueError(f"Invalid TFLite input shape: {inp['shape']}")

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rs: List[str] = []
    rs.append(f"// Generated by {generator_name}\n")
    rs.append(
        f"// TFLite input quantization (documentation): scale={in_scale}, zero_point={in_zp}\n"
    )
    rs.append(f"pub const SAMPLE_RATE: usize = {sample_rate};\n\n")
    rs.append("pub struct TestClip {\n")
    rs.append("    pub expected_label: &'static str,\n")
    rs.append("    pub input: &'static [i8],\n")
    rs.append("}\n\n")

    for i, (_label, audio, _rel_path) in enumerate(clips, 1):
        feats = feature_fn(audio).astype(np.float32).reshape(-1)
        if feats.size != expected_elems:
            raise ValueError(
                f"Feature length {feats.size} != TFLite input elements {expected_elems} "
                f"(shape {inp['shape']})"
            )
        q = np.clip(np.round(feats / in_scale) + in_zp, qmin, qmax).astype(np.int8)
        vals = ", ".join(str(int(v)) for v in q)
        rs.append(f"pub const CLIP_{i}: &[i8] = &[{vals}];\n\n")

    rs.append(f"pub const TEST_CLIPS: [TestClip; {len(clips)}] = [\n")
    for i, (label, _audio, _rel_path) in enumerate(clips, 1):
        rs.append("    TestClip {\n")
        rs.append(f'        expected_label: "{label}",\n')
        rs.append(f"        input: CLIP_{i},\n")
        rs.append("    },\n")
    rs.append("];\n")

    out_path.write_text("".join(rs), encoding="utf-8")
