#!/usr/bin/env python3
"""Generate the C int8 mel-spectrogram test vector that src/main.c feeds
into the cnn_mel model.

Pipeline:
  audio_samples/sincnet_multi_tf.rs (CLIP_N, int8 @ 16 kHz, ~3 s)
    -> dequantize to float using the .rs file's input scale/zero_point
    -> building.utils.create_log_mel_spectrogram (sample_rate=16k, frame_length=1024,
       frame_step=256, custom Rust-parity mel matrix, n_mels=80)
    -> models/cnn_mel_tf.tflite input quant (read via tf.lite.Interpreter)
    -> src/sample_input.[ch]
"""
import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "building"))

import numpy as np  # noqa: E402
import tensorflow as tf  # noqa: E402
from utils import create_log_mel_spectrogram  # noqa: E402


def read_clip(rs_path: Path, clip_n: int):
    text = rs_path.read_text()
    m = re.search(rf"CLIP_{clip_n}: &\[i8\] = &\[(.*?)\];", text, re.S)
    if not m:
        raise SystemExit(f"CLIP_{clip_n} not found in {rs_path}")
    vals = [int(x.strip()) for x in m.group(1).split(",") if x.strip()]

    m = re.search(r"scale=([0-9.eE+-]+),\s*zero_point=(-?\d+)", text)
    if not m:
        raise SystemExit("couldn't find scale=...,zero_point=... in .rs header comment")
    scale = float(m.group(1))
    zp = int(m.group(2))

    labels = re.findall(r'expected_label:\s*"([^"]*)"', text)
    label = labels[clip_n - 1].strip() if clip_n - 1 < len(labels) else "unknown"
    return np.asarray(vals, dtype=np.int8), scale, zp, label


def i8_to_c_array(vals, line_width=16):
    lines = []
    for i in range(0, len(vals), line_width):
        chunk = vals[i:i + line_width]
        lines.append("    " + ", ".join(f"{int(v):>4d}" for v in chunk) + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clip", type=int, default=1)
    ap.add_argument(
        "--audio-rs",
        default=str(REPO / "audio_samples" / "sincnet_multi_tf.rs"),
        help="any of audio_samples/*_tf.rs that contains raw 47872-sample i8 clips",
    )
    ap.add_argument("--tflite", default=str(REPO / "models" / "cnn_mel_tf.tflite"))
    args = ap.parse_args()

    raw_i8, in_scale, in_zp, label = read_clip(Path(args.audio_rs), args.clip)
    audio = (raw_i8.astype(np.float32) - in_zp) * in_scale
    print(f"loaded CLIP_{args.clip}: {len(audio)} samples, label={label!r}")

    mel = create_log_mel_spectrogram(tf.constant(audio, dtype=tf.float32)).numpy()
    print(f"log-mel shape: {mel.shape}  range=[{mel.min():.3f}, {mel.max():.3f}]")

    # cnn_mel's tflite input quantization
    interp = tf.lite.Interpreter(model_path=args.tflite)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out_scale, out_zp = inp["quantization"]
    if out_scale == 0:
        raise SystemExit("cnn_mel input not int8-quantized — wrong tflite?")
    print(f"cnn_mel input quant: scale={out_scale:g}, zp={out_zp}, shape={inp['shape'].tolist()}")

    quantized = np.clip(np.round(mel / out_scale) + out_zp, -128, 127).astype(np.int8).flatten()
    print(f"quantized to {len(quantized)} i8 values")

    src_dir = REPO / "src"
    (src_dir / "sample_input.h").write_text(
        "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n"
        "extern const int8_t g_sample_input[];\n"
        "extern const size_t g_sample_input_len;\n"
        "extern const char *const g_sample_expected_label;\n"
    )
    (src_dir / "sample_input.c").write_text(
        f"// Auto-generated by scripts/gen_mel_input.py from "
        f"audio_samples/sincnet_multi_tf.rs CLIP_{args.clip} (label={label!r}).\n"
        f"// Pipeline: dequantize -> log-mel ({mel.shape[0]} frames x {mel.shape[1]} bins) "
        f"-> int8 quant (scale={out_scale:g}, zp={out_zp}).\n"
        '#include "sample_input.h"\n\n'
        f"const int8_t g_sample_input[] = {{\n{i8_to_c_array(quantized)}\n}};\n"
        f"const size_t g_sample_input_len = {len(quantized)};\n"
        f'const char *const g_sample_expected_label = "{label}";\n'
    )
    print(f"wrote {src_dir / 'sample_input.h'} and sample_input.c")


if __name__ == "__main__":
    main()
